#!/bin/sh
# gen-prompts.sh - bundle the prompt texts into the source, so the
# binary keeps shipping as a single file.
#
# Walks src/prompts for *.txt and writes src/prompts.gen.c (the
# definitions) plus src/prompts.gen.h (the extern declarations). The
# Makefile runs this before every compilation, whenever a txt or this
# script is newer than the generated files: edit the .txt sources and
# rebuild, never edit the generated pair.
#
# Symbol of src/prompts/a/b/c.txt: prompt_a_b_c (every non-alphanumeric
# becomes _). Exactly one trailing newline of each file is stripped -
# internal newlines stay. An empty file (or one holding nothing but the
# trailing newline an editor insists on) becomes an empty string.

set -u
cd "$(dirname "$0")/.." || exit 2

PROMPTS_DIR=src/prompts
OUT_C=src/prompts.gen.c
OUT_H=src/prompts.gen.h

files=$(find "$PROMPTS_DIR" -type f -name '*.txt' 2>/dev/null | LC_ALL=C sort)
if [ -z "$files" ]; then
    echo "gen-prompts: no .txt under $PROMPTS_DIR" >&2
    exit 1
fi

TMP_C="$OUT_C.tmp"
TMP_H="$OUT_H.tmp"
trap 'rm -f "$TMP_C" "$TMP_H"' EXIT INT TERM

cat > "$TMP_C" <<'EOF'
/* prompts.gen.c - generated by tools/gen-prompts.sh from src/prompts.
   Do not edit: change the .txt sources and rebuild. */
#include "prompts.gen.h"
EOF

cat > "$TMP_H" <<'EOF'
/* prompts.gen.h - generated by tools/gen-prompts.sh from src/prompts.
   Do not edit: change the .txt sources and rebuild. One extern per
   bundled text; the definitions live in prompts.gen.c. */
#ifndef LLMKIT_PROMPTS_GEN_H
#define LLMKIT_PROMPTS_GEN_H
EOF

while IFS= read -r f; do
    rel=${f#"$PROMPTS_DIR"/}
    rel=${rel%.txt}
    sym="prompt_$(printf '%s' "$rel" | tr '/.-' '___')"
    case $sym in
        prompt_|*[!A-Za-z0-9_]*)
            echo "gen-prompts: unusable symbol '$sym' for $f" >&2
            exit 1
            ;;
    esac
    printf 'extern const char %s[];\n' "$sym" >> "$TMP_H"

    # 1 when the file ends with a newline: that one byte is stripped
    endsnl=0
    if [ -s "$f" ]; then
        last=$(tail -c 1 "$f" | od -An -tx1 | tr -d ' \n')
        [ "$last" = "0a" ] && endsnl=1
    fi

    {
        printf '\n/* from %s */\n' "$f"
        printf 'const char %s[] =\n' "$sym"
        awk -v src="$f" -v endsnl="$endsnl" '
            {   line = $0
                gsub(/\\/, "\\\\", line)
                gsub(/"/, "\\\"", line)
                gsub(/\t/, "\\t", line)
                L[++n] = line
            }
            END {
                if (n == 0 || (n == 1 && L[1] == "" && endsnl == 1)) {
                    print "    \"\";"
                    exit
                }
                for (i = 1; i < n; i++) printf "    \"%s\\n\"\n", L[i]
                if (endsnl == 1) printf "    \"%s\\n\";\n", L[n]
                else printf "    \"%s\";\n", L[n]
            }
        ' "$f"
    } >> "$TMP_C"
done <<EOF
$files
EOF

printf '#endif\n' >> "$TMP_H"
mv "$TMP_C" "$OUT_C"
mv "$TMP_H" "$OUT_H"
trap - EXIT INT TERM
echo "gen-prompts: $(printf '%s\n' "$files" | wc -l | tr -d ' ') texts bundled"
